import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-zinc-900"
      >
        {/* Headers */}
        <Header />
        
        {/* Main content */}
        <div className="w-full flex items-center justify-center mb-10">
          {children}
        </div>
      </body>
    </html>
  );
}
